name: E2E Testes Robot
on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Install dependencies WebApp
      run: npm install -g wait-on
      
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Install dependencies Tests
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Browser install lib init
      run: rfbrowser init

    - name: Install Serve
      run: npm install -g serve

    - name: Run WeApp
      run: npm start & 
           sleep 15
      env:
        CI: true
        
    - name: Check if Port 3000 is active
      run: netstat -tulpn | grep 3000 || echo "Porta 3000 não está ativa ainda"

    - name: Wait for WebApp
      run: npx wait-on http://localhost:3000 --timeout 600000 --verbose

    - name: Run E2E Tests Robot Framework
      run: robot -d ./logs robot/tests

    - name: Publish Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: robot-test-results
        path: logs/
